=pod

=encoding utf8

=head1 NAME

Text::Tubes - Text and data canalising

=head1 VERSION

This document describes Text::Tubes version 0.01.

=head1 SYNOPSIS

   use Text::Tubes;


=head1 DESCRIPTION

This module allows you to...

=head1 FUNCTIONS

=over

=item B<< loglevel >>

   loglevel('DEBUG');

set the log level, see L<Log::Log4perl::Tiny>.

=item B<< sequence >>

   my $sequence_sub = sequence(@subs_or_tubes);
   my $iterator = $sequence_sub->($some_record);
   1 while defined $iterator->(); # not interested in outputs...

   my $seq_tube = tube(my_sequence => $sequence_sub);
   my $it = $seq_tube->operate($some_other_record);
   # use $it to extract outputs from the sequence

create a sequence of tubes.

=item B<< tube >>

   my $tube = tube($name, $operation);

sugar for creating a L<Text::Tubes::Tube>.

=back

=head1 BUGS AND LIMITATIONS

Report bugs either through RT or GitHub (patches welcome).

=head1 AUTHOR

Flavio Poletti <polettix@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2016 by Flavio Poletti <polettix@cpan.org>

This module is free software. You can redistribute it and/or modify it
under the terms of the Artistic License 2.0.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut
